spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: seata-xa-exception-sample

  main:
    web-application-type: servlet

seata:
  tx-service-group: mygroup
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: XA
  config:
    type: file
  registry:
    type: file

